version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/zno_results
    depends_on:
      - db

  db:
    hostname: postgres-db
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "zno_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"